name = "inventaris-kesamsatan"
compatibility_date = "2026-04-07"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "inventaris_kesamsatan"
database_id = "86f638a8-0f2a-4835-ac14-ca36f401ade5"
